apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-queue-observer
  namespace: windmill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windmill-observer
  template:
    metadata:
      labels:
        app: windmill-observer
        pod_type: permanent_pod
    spec:
      containers:
      - name: windmill-queue-observer
        image: windmill-queue-observer:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: WINDMILL_URL
          value: "http://windmill-app.windmill.svc.cluster.local:8000" # internal service DNS
        - name: WINDMILL_TOKEN
          value: YW5GJry4EODtBJ2vualxFkjmaSnF6vhP
